### ISSUE TITLE
Next 

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2321]

**Comment by EwoutH** [comment]
Experimental designs might be one of the most important new things to support. I encountered this library that might be useful:

- https://github.com/relf/pyDOE3

**Comment by Corvince** [comment]
Nice initiative! One thing to note is that the current `batch_run` function already is somewhat defined around these 3 stages. If you look at the code, it is composed of a "make_kwargs" function (corresponding to stage 1), a "run" function (stage 2.1) and a "collect" function (stage 2.2). Currently it just returns the collected data afterwards in a neutral format (dict), but I originally envisioned a further processing function or functions that do something useful with the result (stage 3). 

So I think your vision aligns nicely with the current structure. And I agree that the most important area of improvement is stage 1 and a clear "run configuration" definition.

**Comment by quaquel** [comment]
I like the conceptual design. I would however design it to be easy to extend / combine with whatever experimental design generator you want to use, rather than try and cover all of that ourselves. The same applies to the subsequent stages.

The motivation for this is that doing large-scale computational experimentation is its own can of worms and not, in my view, the core of the MESA library. It is easy to go overboard with trying to built on this into MESA, but making it less and less useful for others. To wit, last week I spoke with various people who use NetLogo and do large scale uncertainty quantification. None of them use Netlogo's behavior space but all use other packages that interface with NeLogo via java. So, it is more important in my view to establish a clean API for running a single experiment on a MESA model, then do design a very elaborate batch runner.

**Comment by Corvince** [comment]
Agree with @quaquel, but I think this is somewhat in line with what @EwoutH was proposing, in my understanding. The `RunConfiguration` should be that interface. Which tools you use to generate it is up to you, but we provide some basic configuration generators. 

Although maybe `RunConfiguration` should be split into `ModelConfiguration` and `RunConfiguration`. The former details how and individual model should look like, and the latter how it is run. So we create a list(?) of model configurations and then pass that to the run configuration which describes how stage 2 and 3 should be handled.

**Comment by quaquel** [comment]
I guess there is a distinction between inputs to creating experiments and the individual experiments. To start with the latter, this can be as simple as a dict of key value pairs. Typically this will be passed directly to the `__init__` of the model. 

The other is more subtle, and I lack a good name for it. It is basically the parameter space and some density function over this space. in the simplest case, this space is bounded, the axes are orthogonal to one another (i.e., they are independent, that is, there are no correlations), and you assume a uniform distribution over the space (so all points are equally likely). Each of these assumptions can be relaxed but they make your life increasingly more difficult. Moreover, you have to specify how you want to sample points from this space (monte carlo, LHS, some factorial design, etc.), and you have to specify how many points you want to sample. All this interacts in a messy way. For example, if you have a factorial design, you normally specify the number of points on each dimension. If you have a Monte Carlo sampler, you specify how many points in total you wan want to sample. 

Given all this, you have either a collection of experiments or an experiment generator. This you pass to the runner, which then executes them (potentially in parallel). It is only the last task that is properly the batch runner. The rest is the design of experiments.  

an additional minor concern in that you typically want to run each experiment for multiple seeds. You can collapse the seed into the experiment or delay it and let it be handled by the batch runner. Regardless, you need to track the seed number, of course, for replication purposes of each experiment.

**Comment by EwoutH** [comment]
https://github.com/projectmesa/mesa/discussions/2776 implies the importance of allowing users to (easily) construct their own `RunConfiguration`s. Many users have design points from external experimental design tools or specific scenarios they want to test without running all possible combinations.

**Comment by dylan-munson** [comment]
Hi, are there any updates on the status of the batch runner?  I am running into a major issue where if you run the batch runner with multiple iterations and a specified random seed, the same seed is used for each iteration, essentially defeating the purpose of the random seed (see my question at #2835 ).  Most of the workarounds I see involve using a for loop or something similar, but this would make parallelization (which is important for what I am doing) more difficult.  Does anyone have another workaround, or is this something that could be implemented in the near-term?  This seems like a patch that would definitely be useful for a lot of people.

**Comment by EwoutH** [comment]
Thanks for reaching out! I replied in #2835

**Comment by EwoutH** [comment]
Potential GSoC 2026 project: https://github.com/projectmesa/mesa/discussions/2927#discussioncomment-15181136

**Comment by EwoutH** [comment]
So that we don’t forget, something like this might (or might not) be a part of it:
- https://github.com/mesa/mesa/pull/1908

**Comment by usuallycwdillon** [comment]
@dylan-munson and @EwoutH, 
We considered trying to implement our own type of `RunConfiguration` but we were afraid of things breaking if there were an unexpected crash, etc that broke the state of the configuration object. Instead, we solved this for ourselves by writing our `run.py` to accept values from a YAML config file (or use 'default.cfg' when testing) that includes a 'model_params' section as well as a 'execution_metadata' section (describes log-level, output paths, and how data should be taken and saved from the datacollector). Then we could break up the problem into steps, similar to what @quaquel described.

We wrote a `batch_generator.py` that reads a sweep definition YAML (which is basically a definition of the experiment to be conducted) that describes all of the model params with fixed values or lists of values as well as any rules for constraints as well as the execution metadata for running batches (number of iterations to run, and how to increment the seed). For example,

```yaml
sweep_name: "Default Sweep Demonstrator"
description: "A complete sweep definition configuration file with instructions and examples."

execution:
  # some statistically significant number of replications
  replications: 30
  seed_start: 8675309
  # choose from: progressive, random, hash_params, fixed (if fixed, provide a List of seed values - one for each replication) 
  seed_method: "progressive"
  # a run_datetime_00x.cfg will be passed to run.py for each set of replications
  batch_folder: "batch/"
  # output data will stored in this folder/subfolders for each configuration
  output_folder: "batch/results/"
  # time sampling can be: [initial_final, every_week, every_step]
  time_sampling: "every_week"
  # data detail: model, model_teams, model_teams_members
  data_detail: "model_teams"
  # logging level [INFO, DEBUG, WARNING, VALIDATION]
  log_level: "INFO"
  # log to file? (always to terminal)
  log_to_file: True 
  # log_file_name 
  log_file_name: "batch/log/batch.log"

model_parameters:
  ---snip---
  - path: "allow_rotation"
      type: bool 
      # domain: True, False
      values: [False, True] 
  - path: "rotation.rate" # number of team members who rotate out of each team, how often rotations occur
      type: list 
      # domain: integers 1 - team_size, integers 1 - duration_weeks
      values: 
      - [1, 13]
      - [3, 13]
      constraint: "not allow_rotation or (rotation.rate[0] <= team_size and rotation.rate[1] <= duration_weeks)"
  --snip--
```

The `batch_generator.py` reads the sweep file and produces individual 'batch_run_xxx.cfg' files.  These are saved in a folder for use by the `batch_runner.py`, along with a manifest.

Then we wrote our own `batch_runner.py` script that takes arguments for a single run configuration file or folder of configuration files and uses the execution metadata section of the run config to call the `run.py` using the run config, but adjusting the seed and managing the output file names (data and logs) using the execution metadata.  We also have flags to allow for parallel runs (multiple calls to our `run.py`). If the process gets interrupted, the batch_runner compares the output directory contents to the manifest to figure out where it will resume from (`python -m batch_runner batch_run_xxx --resume`).
