### ISSUE TITLE
Integrate CodeCov into Github

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#721]
Figure out how to integrate [CodeCov](https://github.com/apps/codecov) into Github for PRs. 
(This requires admin access, so few can work on this.) 

This issue fixes 1/2 of #720.
Related issue #722.

**Comment by jackiekazil** [comment]
@Corvince  -- It is my understanding to make this work, Mesa needs a .covercov.yml file. I added one to codecov-setup branch. Do you want to propose a setup for the yml or should I? 

RE: https://docs.codecov.io/docs/commit-status

**Comment by Corvince** [comment]
Well, we don't *need* a .covercov.yml file. Adding codecov as a Github App is enough (https://github.com/apps/codecov). You can see how the standard comment/status messages look like [on my fork](https://github.com/Corvince/mesa/pull/4) (where I installed the codecov app). 

So we only need a file if we want to custimize the status messages and/or comments. Here is the default content for reference:

```yaml
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
```
